unicef/etools-fm-fe

src_ts/components/app-shell/app-theme.ts
[ch20459]Color inconsistency on filter elements
=> [ch20458]FM production banner color is non-compliant

package-lock.json, src_ts/components/app-shell/header/page-header.ts
=> Updates package-lock and passes profile info to app selector

assets/i18n/en.json, assets/i18n/ru.json, src_ts/components/app-shell/app-theme.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/styles/radio-button-styles.ts
[ch20338]Option to Clear the On/track - Off/track for overall rating in summary analysis
=> [ch20338]Option to Clear the On/track - Off/track for overall rating in summary analysis

src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/pd-ssfa-details/pd-ssfa-details.tpl.ts
[ch21065] PD/SSFA reference redirects to continuously Loading details page and Progress Reports to 404 - Page Not Found
=> [ch21065] PD/SSFA reference redirects to continuously Loading details page and Progress Reports to 404 - Page Not Found

src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-tab.tpl.ts
[ch21113]Nothing happens when user clicks on Action point Reference
=> [ch21113]Nothing happens when user clicks on Action point Reference

assets/i18n/en.json, assets/i18n/ru.json
[ch21075]FM: Message "No applicable questions found for this question..." needs to be corrected to "No applicable questions found for this section..."
=> [ch21075]FM: Message "No applicable questions found for this question..." needs to be corrected to "No applicable questions found for this section..."

package-lock.json, package.json
[ch21119]Unnecessary Save button in profile dialog
=> [ch21119]Unnecessary Save button in profile dialog

src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/data-collect-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/data-collect-tab.ts
[ch21123] Console error if you Cancel on Add checklist
=> [ch21123] Console error if you Cancel on Add checklist

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/entries-list.ts
[ch21647]Entries for Monitor - Partners: clicking anywhere in the field deletes entered Partner
=> [ch21647]Entries for Monitor - Partners: clicking anywhere in the field deletes entered Partner

.prettierrc, src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.ts
=> [ch21726]Fix add attachment error

src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.ts
=> [ch21805] Can not change attachment

src_ts/components/pages/settings/questions-tab/question-popup/question-popup.ts, src_ts/components/pages/settings/questions-tab/questions-tab.ts
[ch21843] System provided questions edit issues
=> [ch21843] System provided questions edit issues

src_ts/components/pages/settings/questions-tab/questions-tab.ts
[ch21815]Settings: Question Target Level filter not working properly
=> [ch21815]Settings: Question Target Level filter not working properly

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts
[ch21849] Cancel incorrect behavior
=> [ch21849] Cancel incorrect behavior

assets/i18n/en.json, assets/i18n/ru.json, package-lock.json, package.json, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-checklist-attachments-popup/summary-checklist-attachments-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-checklist-attachments-popup/summary-checklist-attachments-popup.ts, src_ts/types/data-collection-findings.types.d.ts
[ch21954] Document type missing
=> [ch21954] Document type missing

src_ts/components/app-shell/app-shell.ts, src_ts/config/config.ts
[ch22297] Drop-down search section is overlapped by app header
=> [ch22297] Drop-down search section is overlapped by app header

src_ts/components/pages/analyze/monitoring-tab/coverage/partnership-tab/partnership-tab.tpl.ts
[ch23778] Missing translations
=> [ch23778] Missing translations

src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts
[ch23881] Analyze: Partner sorting on Visits eligible for HACT Programmatic Visit alters display of details at expand
=> [ch23881] Analyze: Partner sorting on Visits eligible for HACT Programmatic Visit alters display of details at expand

src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/data-collect-popup.ts, src_ts/components/pages/activities-and-data-collection/data-collection/data-collection.ts
[ch23780] Missing toast message
=> [ch23780] Missing toast message

src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.styles.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.ts, src_ts/components/pages/analyze/monitoring-tab/monitoring-tab.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/monitoring-tab.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.ts
[ch22002]Geographic coverage incomplete display of map
=> [ch22002]Geographic coverage incomplete display of map

package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/common/toast-notifications/toast-notification-helper.ts
[ch24197] Use matomo for analytics as in PMP
=> [ch24197] Use matomo for analytics as in PMP

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-monitor-card.ts
[ch23953][Intermittent]Entries to Monitor - selected PD is not displayed(added logs)
=> [ch23953][Intermittent]Entries to Monitor - selected PD is not displayed(added logs)

package-lock.json, package.json, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common/mixins/data-mixin.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-checklist-attachments-popup/summary-checklist-attachments-popup.ts, src_ts/components/pages/settings/questions-tab/question-popup/question-popup.ts
[ch24710] Replace 'performUpdate'
=> [ch24710] Replace 'performUpdate'

src_ts/components/pages/analyze/co-overview-tab/co-overview-tab.ts
[ch24679] Console error in Analyze section
=> [ch24679] Console error in Analyze section

src_ts/components/pages/activities-and-data-collection/activities-page.ts
[ch24746] Background is not entirely blurred when saving sections on form
=> [ch24746] Background is not entirely blurred when saving sections on form

package-lock.json, package.json, src_ts/components/common/attachmants-list/attachments-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-tab.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-attachments-tab/checklist-attachments.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-attachments-tab/checklist-attachments.ts, src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/issue-tracker-list.ts, src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/pd-ssfa-details/pd-ssfa-details.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/checklist-tab/checklist-selection-table/checklist-selection-table.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/data-collect-tab.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/cp-output-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/intervention-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/partner-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/review-tab/review-checklist-item/review-checklist-item.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts, src_ts/components/pages/plan/issue-tracker-tab/issue-tracker-tab.tpl.ts, src_ts/components/pages/plan/templates-tab/templates-tab.tpl.ts, src_ts/components/pages/settings/questions-tab/questions-tab.tpl.ts, src_ts/components/pages/settings/sites-tab/sites-tab.tpl.ts
=> [ch24627] Fix imports

src_ts/components/common/layout/filters/etools-filters-styles.ts, src_ts/components/common/layout/filters/etools-filters.ts
[ch25257] Standardize Clear all action: remove filters from UI and deselect selected filters from the dropdown
=> [ch25257] Standardize Clear all action: remove filters from UI and deselect selected filters from the dropdown

assets/i18n/en.json, assets/i18n/ru.json, src_ts/components/common/mixins/offices-mixin.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.filters.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts, src_ts/types/activities.types.d.ts
=> [ch25270]Make Field Office multi selection

src_ts/components/common/progressbar/proportional-progress-bar.ts
=> [ch25274]Fix UI breaking when minRequired>planned

src_ts/components/pages/settings/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/settings/sites-tab/sites-popup/sites-popup.ts
[ch25299] Site dialog improvements
=> [ch25299] Site dialog improvements

src_ts/components/pages/settings/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/settings/sites-tab/sites-popup/sites-popup.ts
[ch25599] Clicking on Add multiple time adds duplicate locations
=> [ch25599] Clicking on Add multiple time adds duplicate locations

src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts
=> [ch25895]Show arrow to the rigth when left side menu is minimized

src_ts/routing/router.ts, src_ts/routing/routes.ts
=> [ch25900]Browser Back Navigation not working on Tabs with query string

package-lock.json, package.json, src_ts/components/app-shell/app-theme.ts
=> [ch25846]Change module color

src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.tpl.ts
[ch26071] Double Saving data icon
=> [ch26071] Double Saving data icon

src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/activity-summary-tab.ts
=> [ch25824]Fix request with null id

package-lock.json, package.json
=> [ch26374]Update etools-date-time

src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.ts, src_ts/redux/effects/questions.effects.ts
=> [ch26616]Show specific error

src_ts/components/styles/input-styles.ts
[ch26649] Available dates look disabled in the date picker
=> [ch26649] Available dates look disabled in the date picker

src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.filters.ts, src_ts/components/utils/filters-mapping.ts
[ch26679] 'Status' filter to be selected by default on Activities list
=> [ch26679] 'Status' filter to be selected by default on Activities list

src_ts/components/common/layout/filters/etools-filters-styles.ts, src_ts/components/styles/elevation-styles.ts, src_ts/components/styles/shared-styles.ts
[ch26787] Tab navigation: missing focused state for the Create New button
=> [ch26787] Tab navigation: missing focused state for the Create New button

src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts
[ch26791] Tab navigation issues on flow change buttons (Next, Review, Assign and Accept, Finalize)
=> [ch26791] Tab navigation issues on flow change buttons (Next, Review, Assign and Accept, Finalize)

src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/checklist-tab/checklist-selection-table/checklist-selection-table.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/review-tab/review-checklist-item/review-checklist-item.ts, src_ts/types/activities.types.d.ts
=> [ch26837] Use text field for questions

package-lock.json, package.json
[ch27347] Add/Edit Site Specific Location: cannot add Not Active or update to Not Active Sites
=> [ch27347] Add/Edit Site Specific Location: cannot add Not Active or update to Not Active Sites

.eslintrc.json, package-lock.json, package.json, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common/layout/page-content-header/page-content-header.ts, src_ts/components/common/layout/support-btn.ts, src_ts/types/globals.ts, src_ts/types/list-data.types.ts, src_ts/types/monitoring-activity.types.ts, src_ts/types/questions.types.d.ts, src_ts/types/sites.types.ts, src_ts/types/user-model.ts
=> [ch27264]Update linting&formatting tools

src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts
[ch27586] Invalid Action Point Date
=> [ch27586] Invalid Action Point Date

src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.tpl.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.tpl.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.ts
=> [ch27506]Fix auto-validate error

assets/i18n/en.json, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.tpl.ts
[ch27673] Correct label for Edit Points of Note
=> [ch27673] Correct label for Edit Points of Note

assets/i18n/en.json, assets/i18n/ru.json, package-lock.json, package.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/header/page-header.ts
[ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol
=> [ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol

package-lock.json, package.json
=> [ch27921]Update etools-form-builder

package-lock.json, package.json
=> [ch27274]Update lint tools

assets/i18n/en.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts
[ch27925] Correct label for Action Point Popup
=> [ch27925] Correct label for Action Point Popup

package-lock.json, package.json
=> [ch26783] Update tab selection order

src_ts/components/utils/get-location-part.ts
[ch28224] Undefined Locations by admin level
=> [ch28224] Undefined Locations by admin level

src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/completed-finding/completed-finding.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts
=> [ch28262] Add arrow to copy finding answer

src_ts/components/common/location-widget/location-widget.tpl.ts, src_ts/components/common/location-widget/location-widget.ts, src_ts/components/pages/management/sites-tab/sites-tab.tpl.ts, src_ts/types/sites.types.ts
=> [ch28330]Adapt to locations v3.2

src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.ts
[ch28404] Add Site: Site Name validation error not going away
=> [ch28404] Add Site: Site Name validation error not going away

package-lock.json, package.json
[ch28625] Handle security issues on repos
=> [ch28625] Handle security issues on repos

src_ts/types/user-model.ts
=> [ch25430]Boolean values coming as string on user profile endpoint

package-lock.json, package.json, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common/layout/support-btn.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/management/management-page.ts
[ch17503] Update Matomo tracking
=> [ch17503] Update Matomo tracking

package-lock.json, package.json
[ch28079] Migrate to LitElement etools-profile-dropdown component
=> [ch28079] Migrate to LitElement etools-profile-dropdown component

src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/data-collect-popup.ts
[ch29117] Remove unnecessary scroll from dialog
=> [ch29117] Remove unnecessary scroll from dialog

assets/i18n/en.json, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/app-shell/menu/styles/nav-menu-styles.ts, src_ts/components/styles/app-icons.ts
=> [ch29428] Add Implementation Intelligence Link in left menu

src_ts/components/app-shell/menu/app-menu.ts
=> [ch29414]Implem. Intell link

assets/i18n/fr.json, src_ts/components/app-shell/header/page-header.ts
=> [ch30012] Add french translation

src_ts/components/app-shell/menu/app-menu.ts
=> [ch30227] Fix menu tooltips

src_ts/components/app-shell/header/page-header.ts, src_ts/types/user-model.ts
=> [ch30100]Set language from user.preferences.language

src_ts/components/app-shell/header/page-header-styles.ts, src_ts/components/app-shell/header/page-header.ts
[ch30559] Environment label missing
=> [ch30559] Environment label missing

src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.tpl.ts, src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.ts
=> [ch30831]Fix deleted uploaded file still present after save

src_ts/components/pages/activities-and-data-collection/activity-item/checklist-tab/checklist-selection-table/checklist-selection-table.tpl.ts
[ch30829] Review checklist: Adjust checkbox position
=> [ch30829] Review checklist: Adjust checkbox position

.circleci/config.yml, package-lock.json, package.json, src_ts/components/pages/analyze/monitoring-tab/coverage/partnership-tab/partnership-tab.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/coverage/partnership-tab/partnership-tab.ts, src_ts/components/pages/analyze/monitoring-tab/coverage/shared-tab-template.ts, src_ts/components/pages/analyze/monitoring-tab/open-issues-action-points/open-issues-shared-tab-template.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.ts
=> [ch25639]Analyze tab pagination

assets/i18n/fr.json
=> [ch31120]French translation for Answer Types

package-lock.json, package.json, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts
=> [ch31065]Fix intermittent list count not updating

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts
[ch31115] Action Points dialog is not translated - translate link
=> [ch31115] Action Points dialog is not translated - translate link

package-lock.json, package.json, src_ts/components/app-shell/header/page-header.ts
[ch31321] Improve the language dropdown
=> [ch31321] Improve the language dropdown

package-lock.json, package.json, src_ts/components/app-shell/header/page-header.ts, src_ts/components/common/layout/filters/etools-filters.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.tpl.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-tab.tpl.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-tab.ts
=> [ch31299]Dropdown localization

src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/utils/utils.ts, src_ts/config/app-constants.ts, src_ts/redux/reducers/active-language.reducer.ts
[ch31363] [Intermittent] Selected (user) Language not displayed
=> [ch31363] [Intermittent] Selected (user) Language not displayed

src_ts/components/pages/activities-and-data-collection/activity-item/activity-item.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts
=> [ch30790]When in edit mode, disable Submit btn

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/app-shell/app-shell.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common/layout/support-btn.ts
=> [ch31890]Fix app not loading

.circleci/config.yml, src_ts/components/app-shell/app-shell.ts
=> [ch31890]Fix translations applied on property init

src_ts/components/pages/activities-and-data-collection/activity-item/activity-item.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/activity-summary-tab.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts, src_ts/components/styles/app-icons.ts
=> [ch30790]Fix disabled state for action btns on back action, tab nav

package-lock.json, package.json
[ch31669] Correct the doubled label
=> [ch31669] Correct the doubled label

src_ts/components/common/location-widget/location-widget.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.ts
[ch32113] Leaflet: colors overlap location labels
=> [ch32113] Leaflet: colors overlap location labels

src_ts/components/common/location-sites-widget/location-sites-widget.ts, src_ts/components/common/location-widget/location-widget.ts
[ch32119] Leaflet: Selected location not zoomed in when switching between Location by Site / Location By Admin Level
=> [ch32119] Leaflet: Selected location not zoomed in when switching between Location by Site / Location By Admin Level

src_ts/components/app-shell/app-shell.ts
by flagging hasLoadedTranslationFile  as a property
=> [ch31890]Ensure shouldUpdate is triggered

src_ts/components/app-shell/app-shell.ts, src_ts/components/common/map-mixin.ts
[ch32310] Arcgis map fallback show old map
=> [ch32310] Arcgis map fallback show old map

package-lock.json, package.json
[ch32046] Data Collection: Toggles not disabled in View mode
=> [ch32046] Data Collection: Toggles not disabled in View mode

src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/common/attachmants-list/attachments-list.ts, src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.ts, src_ts/components/common/location-widget/location-widget.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-checklist-attachments-popup/summary-checklist-attachments-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/checklist-tab/checklist-selection-table/checklist-selection-table.ts, src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/remove-data-collect-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts, src_ts/components/pages/analyze/co-overview-tab/co-overview-tab.ts, src_ts/components/pages/management/rationale-tab/rationale-tab.ts, src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.ts, src_ts/components/pages/templates/questions-tab/questions-tab.ts, src_ts/components/pages/templates/templates-tab/templates-tab.ts
[ch31300] French translation: Make sure toast messages are translated
=> [ch31300] French translation: Make sure toast messages are translated

package-lock.json, package.json, src_ts/components/app-shell/header/page-header.ts
[ch32646] App selector redirects to not-found before opening the selected app
=> [ch32646] App selector redirects to not-found before opening the selected app 

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/monitor-information-card.ts
=> [ch31783] Visit lead filter

package-lock.json, package.json
[ch32765] Add attachment dialog: attachment type dropdown list is not responsive
WIP
=> [ch32765] Add attachment dialog: attachment type dropdown list is not responsive

src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.styles.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.ts
=> [ch32409] Analysis page map

src_ts/components/app-shell/header/page-header.ts
[ch32541] implement logout with redirect Azure ADB2C with the same effect as the "social/unicef-logout" url has in PRP.
=> [ch32541] implement logout with redirect Azure ADB2C with the same effect as the "social/unicef-logout" url has in PRP.

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-item.ts, src_ts/components/pages/management/management-page.ts, src_ts/components/pages/partners/details/attachements-tab/components/edit-attachments-popup/partner-edit-attachments-popup.tpl.ts, src_ts/components/pages/partners/details/partner-details.ts, src_ts/components/pages/partners/list/add-new-vendor/add-new-vendor-popup.tpl.ts, src_ts/components/pages/partners/list/add-new-vendor/add-new-vendor-popup.ts, src_ts/components/pages/partners/list/partners-list.tpl.ts, src_ts/components/pages/partners/list/partners-list.ts, src_ts/components/styles/button-styles.ts, src_ts/redux/effects/tpm-partners.effects.ts
[ch33353] TPM list moved to FM issues
=> [ch33353] TPM list moved to FM issues

src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/pd-ssfa-details/pd-ssfa-details.tpl.ts, src_ts/components/pages/analyze/co-overview-tab/cp-details-item/cp-details-item.tpl.ts
[ch27497] Handle apps that reference URLs from PMP, which have changed in the new version of PMP
=> [ch27497] Handle apps that reference URLs from PMP, which have changed in the new version of PMP

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/partners/details/details-tab/partner-contacts/partner-contacts.tpl.ts, src_ts/components/pages/partners/details/details-tab/partner-contacts/partner-contacts.ts, src_ts/components/pages/partners/details/details-tab/partner-details-tab.ts, src_ts/components/pages/partners/details/partner-details.ts, src_ts/components/pages/partners/list/add-new-vendor/add-new-vendor-popup.ts
[ch32752] AMP - Improvements, apps `amp` branch updates
=> [ch32752] AMP - Improvements, apps `amp` branch updates

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.tpl.ts
[ch33618] Date format prevents visit save
=> [ch33618] Date format prevents visit save

src_ts/components/pages/partners/list/partners-list.ts
=> [ch33614] TPM layout issues

src_ts/components/pages/activities-and-data-collection/data-collection/data-collection.ts
[ch33626] Data collection cannot be added/updated
=> [ch33626] Data collection cannot be added/updated

src_ts/components/pages/templates/questions-tab/question-popup/question-popup.ts
=> [ch33659]Fix dropdown first selection

src_ts/components/pages/partners/details/details-tab/partner-contacts/partner-contacts.tpl.ts, src_ts/components/pages/partners/details/details-tab/partner-contacts/partner-contacts.ts, src_ts/types/activities.types.d.ts
[ch33671] AMP: changes and performance improvements
=> [ch33671] AMP: changes and performance improvements

src_ts/components/pages/analyze/co-overview-tab/co-overview-tab.tpl.ts
[ch33810] Analysis: Cannot expand CP Outcome details
=> [ch33810] Analysis: Cannot expand CP Outcome details

src_ts/components/pages/partners/list/partners-list.tpl.ts, src_ts/components/pages/partners/list/partners-list.ts, src_ts/components/utils/utils.ts, src_ts/redux/selectors/tpm-partners.selectors.ts
[ch34000] Third Party Monitors - Add new vendor button available to everybody
=> [ch34000] Third Party Monitors - Add new vendor button available to everybody

package-lock.json, package.json, src_ts/components/pages/templates/templates-tab/templates-tab.ts, src_ts/redux/effects/app.effects.ts
[ch34047] Filtering of Templates/ Questions error, Table pagination broken in all pages
=> [ch34047] Filtering of Templates/ Questions error, Table pagination broken in all pages

src_ts/components/pages/activities-and-data-collection/activity-item/activity-item.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/activity-details-tab.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/entries-list.ts
[ch34038] Empty UI and console error when navigating from Form to Visit Details after page refresh
=> [ch34038] Empty UI and console error when navigating from Form to Visit Details after page refresh

.circleci/config.yml, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.filters.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/types/static-data.types.d.ts
[ch34080] Hide filters for TPM staff members
=> [ch34080] Hide filters for TPM staff members

src_ts/components/pages/templates/templates-tab/templates-tab.ts
[ch34137] Can not load Question Templates List
=> [ch34137] Can not load Question Templates List

src_ts/components/pages/activities-and-data-collection/activity-item/activity-item.ts, src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/additional-info-tab.ts, src_ts/components/pages/analyze/co-overview-tab/co-overview-tab.tpl.ts, src_ts/components/pages/analyze/co-overview-tab/co-overview-tab.ts, src_ts/components/pages/analyze/co-overview-tab/cp-details-item/cp-details-item.tpl.ts, src_ts/components/pages/analyze/co-overview-tab/cp-details-item/cp-details-item.ts
[ch34006] Irrelevant links for team member of type tpm user
=> [ch34006] Irrelevant links for team member of type tpm user

package-lock.json, package.json, src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/organizations-dropdown.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/monitor-information-card.ts, src_ts/redux/effects/app.effects.ts
=> [ch33990]Fix user display lag- show 'Loading..' msg until users are loaded

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/partners/details/details-tab/partner-contacts/partner-contacts.tpl.ts
=> [ch34085]Replace Inoperative with No Access

package-lock.json, package.json
=> [ch34140]Language header is not sent on certain endpoints

src_ts/components/app-shell/app-shell-styles.ts
[ch34174]  Visit details page: Loading overlay not stretching on the whole page
=> [ch34174]  Visit details page: Loading overlay not stretching on the whole page

src_ts/components/pages/templates/questions-tab/questions-tab.ts
[ch34219] Filtering inconsistency
=> [ch34219] Filtering inconsistency

src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts
=> [ch34109]Unprefix users in filters - iterate over the array

src_ts/components/common/mixins/list-mixin.ts, src_ts/components/pages/templates/questions-tab/questions-tab.ts, src_ts/components/pages/templates/templates-tab/templates-tab.tpl.ts, src_ts/components/pages/templates/templates-tab/templates-tab.ts, src_ts/components/utils/utils.ts
[ch34208] Tab navigation on Templates fails when the page is loading selections in filters
=> [ch34208] Tab navigation on Templates fails when the page is loading selections in filters

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/monitor-information-card.ts
=> [ch34331]Visit Lead not displayed when different from team members

src_ts/components/pages/partners/list/partners-list.tpl.ts
[ch34392] UNICEF User PME can export an empty list
=> [ch34392] UNICEF User PME can export an empty list

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, polymer.json, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/additional-info-tab.ts, src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/pd-ssfa-details/pd-ssfa-details.tpl.ts, src_ts/components/pages/analyze/co-overview-tab/cp-details-item/cp-details-item.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/coverage/pd-spd-tab/pd-spd-tab.ts, src_ts/components/pages/analyze/monitoring-tab/coverage/pd-ssfa-tab/pd-ssfa-tab.ts, src_ts/components/pages/analyze/monitoring-tab/monitoring-tab.navigation.constants.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts, src_ts/components/utils/findings-and-overall-sort.ts, src_ts/routing/component-lazy-load-config.ts
=> [ch32140]Rename SSFA to SPD

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.filters.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/types/activities.types.d.ts
=> [ch34725]Sections filter for activities list

src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.ts
=> [ch34615]Filter out TPM users from Action Points

package-lock.json, package.json
=> [ch32140]Update etools-form-builder

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/base-details-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts, src_ts/components/utils/utils.ts
[ch34622] Toast displays incorrectly when no "Entities to monitor" are selected
=> [ch34622] Toast displays incorrectly when no "Entities to monitor" are selected

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts
[ch34805] 'Unknown error'  appears too often
=> [ch34805] 'Unknown error'  appears too often

src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/activities-and-data-collection/activities-page.ts
[ch34799] Forever Loading state when you refresh the add new activity page
=> [ch34799] Forever Loading state when you refresh the add new activity page

assets/css/app-theme.css, index.html, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.tpl.ts, src_ts/components/common/attachmants-list/remove-attachment-popup/remove-attachment-popup.tpl.ts, src_ts/components/common/file-components/file-select-input.ts, src_ts/components/common/file-components/files-popup.ts, src_ts/components/common/layout/support-btn.ts, src_ts/components/common/location-sites-widget/location-sites-widget.tpl.ts, src_ts/components/common/location-widget/location-widget.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.styles.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-checklist-attachments-popup/summary-checklist-attachments-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/data-collect-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/data-collect-tab/remove-data-collect-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/cp-output-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/intervention-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/partner-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/reason-popup.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts, src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/partners/details/attachements-tab/components/edit-attachments-popup/partner-edit-attachments-popup.tpl.ts, src_ts/components/pages/partners/details/attachements-tab/components/remove-attachment-popup/partner-remove-attachment-popup.tpl.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.tpl.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.tpl.ts, src_ts/components/pages/templates/questions-tab/question-tab.styles.ts, src_ts/components/pages/templates/questions-tab/questions-tab.tpl.ts, src_ts/components/styles/dialog-styles.ts
[ch35621] Shoelace migration filters, dialog, buttons, styles fixes
=> [ch35621] Shoelace migration filters, dialog, buttons, styles fixes

src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/components/pages/partners/list/partners-list.tpl.ts, src_ts/components/pages/partners/list/partners-list.ts, src_ts/components/styles/shared-styles.ts
Fix filters alignment + fix page-content-header
=> Fix filters alignment + fix page-content-header

src_ts/components/common/attachmants-list/edit-attachments-popup/edit-attachments-popup.tpl.ts, src_ts/components/common/attachmants-list/remove-attachment-popup/remove-attachment-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/entries-list.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/monitor-information-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts, src_ts/components/pages/activities-and-data-collection/data-collection/data-collection.ts, src_ts/components/pages/management/rationale-tab/annual-fm-rationale/annual-fm-rationale.tpl.ts, src_ts/components/pages/management/rationale-tab/rationale.styles.ts, src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/management/sites-tab/sites-tab.ts, src_ts/components/pages/partners/details/attachements-tab/components/edit-attachments-popup/partner-edit-attachments-popup.tpl.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.styles.ts, src_ts/components/styles/app-icons.ts, src_ts/components/styles/card-styles.ts, src_ts/components/styles/input-styles.ts, src_ts/components/styles/radio-button-styles.ts, src_ts/components/styles/shared-styles.ts
=> Shoelace migration fixes

src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/templates/issue-tracker-tab/issue-tracker-popup/issue-tracker-popup.ts
=> Fix dialog events

package-lock.json, package.json, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts, src_ts/components/pages/management/sites-tab/sites-popup/sites-popup.tpl.ts, src_ts/components/pages/partners/list/add-new-vendor/add-new-vendor-popup.tpl.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.styles.ts, src_ts/components/pages/templates/questions-tab/question-tab.styles.ts, src_ts/components/pages/templates/templates-tab/templates-tab.styles.ts, src_ts/components/styles/card-styles.ts, src_ts/components/styles/shared-styles.ts
Style fixes + filters fix on page refresh
=> Style fixes + filters fix on page refresh

package-lock.json, package.json
[ch35941] Dropdown doesn't open when it's populated
=> [ch35941] Dropdown doesn't open when it's populated

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/app-shell/menu/app-menu.ts
[ch35015] Dashboard link on main fmm page
=> [ch35015] Dashboard link on main fmm page

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.filters.ts
[ch31176] Add filter in the FM visits
=> [ch31176] Add filter in the FM visits

assets/i18n/fr.json, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts
[ch36030] FM Shoelace Migration 4
=> [ch36030] FM Shoelace Migration 4

assets/i18n/en.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.styles.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.tpl.ts, src_ts/components/pages/templates/questions-tab/question-popup/question-popup.ts, src_ts/types/questions.types.d.ts
[ch35481] When adding new questions there is no way to move order
=> [ch35481] When adding new questions there is no way to move order

src_ts/components/pages/analyze/analyze-page.ts, src_ts/components/pages/management/management-page.ts, src_ts/components/pages/templates/templates-page.ts
=> Fix navigation issue when only tpm

assets/i18n/ar.json, assets/i18n/es.json, src_ts/components/app-shell/header/header-dropdown-styles.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/config/app-constants.ts
[ch36375] Add arabic and spanish translations
=> [ch36375] Add arabic and spanish translations

src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/pd-ssfa-details/pd-ssfa-details.tpl.ts, src_ts/components/pages/analyze/co-overview-tab/cp-details-item/cp-details-item.tpl.ts
[ch34961][Shoelace]- PMP Reports page cant be accessed
=> [ch34961][Shoelace]- PMP Reports page cant be accessed

src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/reason-popup.ts, src_ts/components/pages/partners/details/partner-details.ts
=> [ch36397] Translation issues

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/components/app-shell/header/countries-dropdown.ts, src_ts/components/app-shell/header/organizations-dropdown.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/pages/partners/details/details-tab/partner-contacts/partner-contacts.ts, src_ts/components/pages/partners/details/details-tab/partner-information/partner-information.ts, src_ts/redux/store.ts
=> [ch36579] PWA Helpers

package-lock.json, package.json
[ch36712] Improve readability, update font-size
=> [ch36712] Improve readability, update font-size

package-lock.json, package.json, src_ts/components/app-shell/header/page-header-styles.ts, src_ts/components/app-shell/header/page-header.ts, src_ts/components/common/attachmants-list/attachments-list.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/note-card.ts, src_ts/components/pages/analyze/monitoring-tab/geographic-coverage/geographic-coverage.styles.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.tpl.ts, src_ts/components/pages/analyze/monitoring-tab/visits-eligible-for-hact/visits-eligible-for-hact.ts
=> [ch36767 FM Mobile Issues 2

src_ts/components/common/location-widget/location-widget.styles.ts, src_ts/components/pages/activities-and-data-collection/activity-item/activity-item.ts
Fixed map style, updated Duplicate logic to include reviewer
=> Fixed map style, updated Duplicate logic to include reviewer

package-lock.json, package.json, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-list-and-popups/intervention-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/entities-monitor-card/entities-monitor-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts
=> [ch37117] FM improvements

src_ts/components/common/location-sites-widget/location-sites-widget.tpl.ts, src_ts/components/common/location-widget/location-widget.styles.ts
#Staging  Hotfix sites panel overflow
=> #Staging Hotfix sites panel overflow

package-lock.json, package.json
[ch37195] Cannot select Checklist/Review tab when creating a new visit
=> [ch37195] Cannot select Checklist/Review tab when creating a new visit

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/ru.json, package-lock.json, package.json
[ch32103] Change button names in Report Review State
=> [ch32103] Change button names in Report Review State

src_ts/components/app-shell/menu/app-menu.ts, src_ts/components/pages/analyze/analyze-page.ts, src_ts/routing/subpage-redirect.ts
[ch35939] Hide Field Monitoring analysis page
=> [ch35939] Hide Field Monitoring analysis page

src_ts/components/common/location-sites-widget/location-sites-widget.tpl.ts
[ch37079] In FM location by admin selection modify the link to send the user to "sites" in management tab if no sites are available
=> [ch37079] In FM location by admin selection modify the link to send the user to "sites" in management tab if no sites are available

src_ts/components/pages/activities-and-data-collection/data-collection/data-collection.ts
[ch31718] Add an export button that bring up the browser print option. FM Data Collection by method
=> [ch31718] Add an export button that bring up the browser print option. FM Data Collection by method

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/confirm-submit-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/reason-popup.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/statuses-actions.ts, src_ts/redux/reducers/activity-summary.reducer.ts, src_ts/redux/selectors/activity-summary.selectors.ts, src_ts/types/activities.types.d.ts, src_ts/types/redux-types.d.ts
=> [ch37262] Action Points

src_ts/components/common/mixins/cp-outputs-mixin.ts, src_ts/components/common/mixins/interventions-mixin.ts, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.tpl.ts, src_ts/components/pages/activities-and-data-collection/activity-item/action-points-tab/action-points-popup/action-points-popup.ts, src_ts/endpoints/endpoints-list.ts, src_ts/types/redux-types.d.ts
[ch37382] FM Action points- output and PD
=> [ch37382] FM Action points- output and PD

src_ts/components/pages/activities-and-data-collection/activities-page.ts, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/monitor-information-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/report-reviewer-popup.ts, src_ts/endpoints/endpoints-list.ts, src_ts/redux/selectors/static-data.selectors.ts, src_ts/types/redux-types.d.ts
=> [ch37260] Report reviewer

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts, src_ts/types/activities.types.d.ts
[ch37583] Remote monitoring radio button
=> [ch37583] Remote monitoring radio button

src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.tpl.ts, src_ts/components/pages/activities-and-data-collection/activities-list/activities-list.ts, src_ts/endpoints/endpoints-list.ts
[ch37411] Export for visits page
=> [ch37411] Export for visits page

src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/monitor-information-card.ts, src_ts/components/pages/activities-and-data-collection/activity-item/statuses-actions/report-reviewer-popup.ts, src_ts/redux/selectors/static-data.selectors.ts
Report Reviewers considers all staff users
=> Report Reviewers considers all staff users

src_ts/components/pages/activities-and-data-collection/activity-item/activity-summary-tab/summary-card.ts, src_ts/types/activities.types.d.ts
[ch36598] Mandatory questions and fields
=> [ch36598] Mandatory questions and fields

package-lock.json, package.json
[ch39626] [FM] Some drop-down lists are not working properly
=> [ch39626] [FM] Some drop-down lists are not working properly

package-lock.json, package.json, src_ts/components/pages/activities-and-data-collection/activity-item/collect-tab/collect-tab.ts, src_ts/components/pages/activities-and-data-collection/activity-item/summary-tab/summary-card.ts, src_ts/components/pages/activities-and-data-collection/data-collection/data-collection.ts, src_ts/redux/selectors/attachments-list.selectors.ts
[ch39799] FM: css styling displayed in Summary and in pdf export
=> [ch39799] FM: css styling displayed in Summary and in pdf export

src_ts/components/pages/activities-and-data-collection/activity-item/additional-info-tab/pd-ssfa-details/pd-ssfa-details.tpl.ts
[ch38708] Bring in partner reports to FMM
=> [ch38708] Bring in partner reports to FMM

src_ts/components/common/location-widget/location-widget.ts, src_ts/redux/actions/widget-locations.actions.ts, src_ts/redux/effects/widget-locations.effects.ts, src_ts/redux/reducers/widget-locations.reducer.ts, src_ts/types/redux-types.d.ts
[ch38633] March- Feature Enhancement Request: Improve Site Selection Visibility in FMM
=> [ch38633] March- Feature Enhancement Request: Improve Site Selection Visibility in FMM

src_ts/components/pages/activities-and-data-collection/activity-item/summary-tab/summary-card.ts
Fix display for add action point
=> Fix display for add action point

assets/i18n/ar.json, assets/i18n/en.json, assets/i18n/es.json, assets/i18n/fr.json, assets/i18n/ru.json, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/base-details-card.ts, src_ts/types/activities.types.d.ts
[ch36919] May 2025- FMM trigger when same location or partner or PD is visited second or more times per calendar year
=> [ch36919] May 2025- FMM trigger when same location or partner or PD is visited second or more times per calendar year

src_ts/components/common/attachmants-list/attachments-list.tpl.ts, src_ts/types/attachment.types.d.ts
[ch38354] May 2025- Attachment categories revision
=> [ch38354] May 2025- Attachment categories revision

package-lock.json, package.json, src_ts/components/pages/activities-and-data-collection/activity-item/details-tab/details-cards/activity-details-card/activity-details-card.ts
=> Fix tooltips

src_ts/components/pages/templates/questions/question-popup/question-popup.tpl.ts
=> [257185] Fix

src_ts/components/common/location-widget/location-widget.tpl.ts, src_ts/types/sites.types.ts
=> 273143 WIP - Hide location

src_ts/components/common/location-widget/location-widget.tpl.ts
=> Fix locations filter inactive
